In [49]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes 

In [50]:
x,y= load_diabetes(return_X_y=True)

In [51]:
df=pd.read_csv('placement.csv')

In [52]:
df

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [3]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [4]:
x.shape

(442, 10)

In [5]:
y.shape

(442,)

In [7]:
# Using Sklear's Linear Regression

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=2)

In [13]:
print(x_train.shape)
print(x_test.shape)

(353, 10)
(89, 10)


In [14]:
from sklearn.linear_model import LinearRegression

In [16]:
reg.fit(x_train, y_train)

LinearRegression()

In [17]:
y_pred=reg.predict(x_test)

In [20]:
from sklearn.metrics import r2_score

In [24]:
r2_score(y_test,y_pred)

0.4399338661568968

In [25]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [26]:
reg.intercept_


np.float64(151.88331005254167)

# Ab banayenge apna khud ka Linear Regrssion Class

In [32]:
class MeraLR:
    
    def __init__(self):
        self.coef_=None
        self.intercept_=None
    
    def fit(self,x_train,y_train):
        x_train=np.insert(x_train,0,1,axis=1)
        
        #calculate coeffs
        betas=np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
        self.intercept_=betas[0]
        self.coef_=betas[1:]
        
        
    def predict(self,x_test):
        y_pred=np.dot(x_test,self.coef_)+self.intercept_
        return y_pred
    
   


In [36]:
lr=MeraLR()

In [37]:
lr.fit(x_train, y_train)

In [38]:
# np.insert(jema change karvanu che ae , kaya column , kayi value enter kaarvani che , axix =1 --> for column)

In [42]:
y_pred=lr.predict(x_test)

In [44]:
from sklearn.metrics import r2_score

r2_score(y_test,y_pred)

0.4399338661568969

In [45]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [46]:
lr.intercept_

np.float64(151.88331005254167)

# let's use this multiple reg.. class for single column

In [80]:
x=df.iloc[:,0:1]
y=df.iloc[:,1:]

In [81]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.3, random_state=2)

In [82]:
lr=MeraLR()

In [83]:
lr.fit(x_train,y_train)

In [84]:
y_pred=lr.predict(x_test)
y_pred

array([[3.89015204],
       [3.09544039],
       [2.38964753],
       [2.57859995],
       [1.66162498],
       [1.78388831],
       [2.07843178],
       [2.93427509],
       [3.76233128],
       [2.93983252],
       [4.09021931],
       [3.5122472 ],
       [2.97317706],
       [2.4063198 ],
       [3.1899166 ],
       [3.46778781],
       [1.95061103],
       [3.24549084],
       [2.97873449],
       [3.41777099],
       [2.56192768],
       [3.16768691],
       [2.86202858],
       [3.12322751],
       [3.68452735],
       [2.87314343],
       [3.49557493],
       [3.34552448],
       [3.91793916],
       [1.9672833 ],
       [3.6511828 ],
       [3.2121463 ],
       [3.74010159],
       [2.78978207],
       [2.78422464],
       [3.27327796],
       [3.52891947],
       [2.61750192],
       [2.66196131],
       [2.71753555],
       [3.08988297],
       [4.08466188],
       [2.13400602],
       [1.95616845],
       [3.44000069],
       [2.87870085],
       [2.95094737],
       [2.834

In [85]:
y_pred

array([[3.89015204],
       [3.09544039],
       [2.38964753],
       [2.57859995],
       [1.66162498],
       [1.78388831],
       [2.07843178],
       [2.93427509],
       [3.76233128],
       [2.93983252],
       [4.09021931],
       [3.5122472 ],
       [2.97317706],
       [2.4063198 ],
       [3.1899166 ],
       [3.46778781],
       [1.95061103],
       [3.24549084],
       [2.97873449],
       [3.41777099],
       [2.56192768],
       [3.16768691],
       [2.86202858],
       [3.12322751],
       [3.68452735],
       [2.87314343],
       [3.49557493],
       [3.34552448],
       [3.91793916],
       [1.9672833 ],
       [3.6511828 ],
       [3.2121463 ],
       [3.74010159],
       [2.78978207],
       [2.78422464],
       [3.27327796],
       [3.52891947],
       [2.61750192],
       [2.66196131],
       [2.71753555],
       [3.08988297],
       [4.08466188],
       [2.13400602],
       [1.95616845],
       [3.44000069],
       [2.87870085],
       [2.95094737],
       [2.834

In [86]:
r2_score(y_test,y_pred)

0.7736419609402817