<b> What is Numpy ? </b></br>
<b>--> </b> Numpy is a package for scientific computing in python . Main thing is Numpy Array
</br>
<b>--> </b> Numpy is basically buit in C and make wrapper to use in python because its syntax is very easy so for that easy to learn.


<h1>Creating Numpy Arrays</h1>

In [2]:
#np.array
import numpy as np

a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#2d and 3d
b=np.array([[1,2,3],[4,5,6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [4]:
#3d
np.array([ [ [1,2,3],[4,5,6]],[[7,8,9],[9,8,7]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [9, 8, 7]]])

In [8]:
d=np.array([1,2,3],dtype=float)
print(d)

[1. 2. 3.]


In [9]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
# reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [12]:
np.arange(1,17).reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [13]:
#np.ones and np.zeroes
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.random.random((2,3))

array([[0.05643045, 0.46100569, 0.38095298],
       [0.33209044, 0.69982292, 0.14405293]])

In [29]:
# np.linspace
np.linspace(-10,10,10 ,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [28]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h1> Array Atribute</h1>

Every numpy array is object of Numpy class and this object means numpy array can use attribute of Numpy class

In [44]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [45]:
#ndim
a2.ndim

2

In [46]:
#shape
a2.shape

(3, 4)

In [47]:
#size
a3.size

8

In [51]:
#itemsize (what much each item occupy memory)
a1.itemsize

4

In [50]:
# dtype
print(a1.dtype)

int32


<h1> Changing datatype </h1>

In [56]:
#astype
a2=a1.astype(np.int64)
a2.dtype

dtype('int64')

<h1> Array Operation </h1>

In [58]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [59]:
# scaler operation

#arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [60]:
#relation

a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [61]:
#vector operation

#arithmetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [62]:
 a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

<h1> Array Function</h1>

In [65]:
a1=np.random.random((3,4))
a1=np.round(a1*100)
a1

array([[11., 40., 18., 69.],
       [15., 67., 83., 88.],
       [80., 45., 81., 45.]])

In [67]:
#max/min/prod
# axis =0,1 --> 0-column ,1- row
np.sum(a1,axis=1)

array([138., 253., 251.])

In [68]:
np.max(a1,axis=0)

array([80., 67., 83., 88.])

In [69]:
# mean/median/std/var
np.var(a1)
np.mean(a1,axis=0)

array([35.33333333, 50.66666667, 60.66666667, 67.33333333])

In [72]:
# dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [74]:
# log and exponents

np.log(a1)
np.exp(a1)

array([[5.98741417e+04, 2.35385267e+17, 6.56599691e+07, 9.25378173e+29],
       [3.26901737e+06, 1.25236317e+29, 1.11286375e+36, 1.65163625e+38],
       [5.54062238e+34, 3.49342711e+19, 1.50609731e+35, 3.49342711e+19]])

In [76]:
#random/floor/cell
#ceil (2,7 ->2)
#floor (3.1 -->4)

np.round (np.random.random((2,3))*100)

array([[36., 85., 58.],
       [29., 98., 43.]])

# Indexing and slicing

In [77]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [79]:
#indexing

#1D

a1[0]

np.int64(0)

In [80]:
#2D

a2[1,2]

np.int64(6)

In [83]:
#3d

a3[1,1,1]

np.int64(7)

In [86]:
#Slicing
#1d

a1[1:7:2]

array([1, 3, 5])

In [88]:
#2d

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
#practice this all

a2[0,:]

array([0, 1, 2, 3])

In [91]:
a2[:,2]

array([ 2,  6, 10])

In [92]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [94]:
a2[ : : 2 , : : 3]

array([[ 0,  3],
       [ 8, 11]])

In [95]:
a2[: : 2, 1: : 2]

array([[ 1,  3],
       [ 9, 11]])

In [96]:
a2[1 , : : 3]

array([4, 7])

In [97]:
a2 [0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [101]:

# 3D

a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [102]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [103]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [106]:
a3[0,1,:]

array([3, 4, 5])

In [107]:
a3[1,:,1]

array([10, 13, 16])

In [108]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [110]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [112]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [114]:
for i in a2:
    print(a2)
    print("")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



In [115]:
for i in a3:
    print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [118]:
# nditer


for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [119]:
# reshape (Already leanred)



In [139]:
# Transpose
a1=np.arange(12).reshape(3,4)
a2=a1.T
a2.shape



(4, 3)

In [140]:
# ravel (conver any dimesional array  --> 1D

a2.ravel()

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

# Stacking

In [141]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)



In [143]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [144]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# splitting

In [146]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [147]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]