### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([98, 15, 95, 95, 67, 10, 37, 96, 87, 56, 66, 98, 91, 41, 92])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[81, 72, 85, 32],
       [18,  4,  2, 18],
       [55, 99,  6, 13],
       [17, 25, 22, 82],
       [24, 94, 66, 46],
       [ 6, 42, 15, 40]])

In [6]:
# desecending
np.sort(a)[::-1]

array([98, 98, 96, 95, 95, 92, 91, 87, 67, 66, 56, 41, 37, 15, 10])

In [5]:
np.sort(b,axis=1)

array([[32, 72, 81, 85],
       [ 2,  4, 18, 18],
       [ 6, 13, 55, 99],
       [17, 22, 25, 82],
       [24, 46, 66, 94],
       [ 6, 15, 40, 42]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [7]:
# code
np.append(a,200)

array([ 98,  15,  95,  95,  67,  10,  37,  96,  87,  56,  66,  98,  91,
        41,  92, 200])

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [10]:
np.append(b,np.ones((1,b.shape[1])),axis=0)

array([[81., 72., 85., 32.],
       [18.,  4.,  2., 18.],
       [55., 99.,  6., 13.],
       [17., 25., 22., 82.],
       [24., 94., 66., 46.],
       [ 6., 42., 15., 40.],
       [ 1.,  1.,  1.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [12]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [14]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [15]:
len(np.unique(e))


6

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [19]:
# code
a.shape

(15,)

In [20]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1)

array([[11],
       [53],
       [28],
       [50],
       [38],
       [37],
       [94],
       [92],
       [ 5],
       [30],
       [68],
       [ 9],
       [78],
       [ 2],
       [21]])

In [26]:
np.expand_dims(np.random.random((3,3,3)),axis=1).shape

(3, 1, 3, 3)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  6,  7, 10, 12]),)

In [ ]:
# replace all values > 50 with 0
# np.where(condition, true part, false part)
np.where(a>50,0,a)

array([11,  0, 28, 50, 38, 37,  0,  0,  5, 30,  0,  9,  0,  2, 21])

In [ ]:
np.where(a%2 == 0,0,a)

array([11, 53,  0,  0,  0, 37,  0,  0,  5,  0,  0,  9,  0,  0, 21])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.argmax(a)

6

In [29]:
b

array([[81, 72, 85, 32],
       [18,  4,  2, 18],
       [55, 99,  6, 13],
       [17, 25, 22, 82],
       [24, 94, 66, 46],
       [ 6, 42, 15, 40]])

In [30]:
np.argmax(b,axis=1)

array([2, 0, 1, 3, 1, 1])

In [32]:
np.argmax(b,axis=0)

array([0, 2, 0, 3])

In [33]:
# np.argmin
np.argmin(a)

np.int64(5)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.cumsum(a)

array([ 11,  64,  92, 142, 180, 217, 311, 403, 408, 438, 506, 515, 593,
       595, 616])

In [36]:
b

array([[81, 72, 85, 32],
       [18,  4,  2, 18],
       [55, 99,  6, 13],
       [17, 25, 22, 82],
       [24, 94, 66, 46],
       [ 6, 42, 15, 40]])

In [38]:
np.cumsum(b,axis=0)

array([[ 81,  72,  85,  32],
       [ 99,  76,  87,  50],
       [154, 175,  93,  63],
       [171, 200, 115, 145],
       [195, 294, 181, 191],
       [201, 336, 196, 231]])

In [39]:
#if we not apply axis them it convert into 1D array and then do cummulative sum on it
np.cumsum(b)

array([ 81, 153, 238, 270, 288, 292, 294, 312, 367, 466, 472, 485, 502,
       527, 549, 631, 655, 749, 815, 861, 867, 909, 924, 964])

In [ ]:
# np.cumprod
np.cumprod(a)

array([                  11,                  583,                16324,
                     816200,             31015600,           1147577200,
               107872256800,        9924247625600,       49621238128000,
           1488637143840000,   101227325781120000,   911045932030080000,
       -2725393596491966464, -5450787192983932928, -3786066610405281792])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [41]:
a

array([98, 15, 95, 95, 67, 10, 37, 96, 87, 56, 66, 98, 91, 41, 92])

In [42]:
np.percentile(a,50)

np.float64(87.0)

In [43]:
np.median(a)

np.float64(87.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [47]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90])

(array([0, 2, 0, 1, 1, 1, 2, 0, 1]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [45]:
np.histogram(a,bins=[0,25,50,75,100])

(array([2, 2, 3, 8]), array([  0,  25,  50,  75, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [51]:
np.corrcoef(np.linspace(-10,10,10),np.linspace(48,50,10))

array([[1., 1.],
       [1., 1.]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [81]:
# code
a


array([110, 530,  95,  95,  67,  10,  37,  96,  87,  56,  66,  98,  91,
        41,  92])

In [82]:
items = [110,67,96,40,50,60,70,80,90,100]

np.isin(a,items)

array([ True, False, False, False,  True, False, False,  True, False,
       False, False, False, False, False, False])

In [83]:
a[np.isin(a,items)]

array([110,  67,  96])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.flip(a)

array([21,  2, 78,  9, 68, 30,  5, 92, 94, 37, 38, 50, 28, 53, 11])

In [55]:
b

array([[81, 72, 85, 32],
       [18,  4,  2, 18],
       [55, 99,  6, 13],
       [17, 25, 22, 82],
       [24, 94, 66, 46],
       [ 6, 42, 15, 40]])

In [56]:
np.flip(b)

array([[40, 15, 42,  6],
       [46, 66, 94, 24],
       [82, 22, 25, 17],
       [13,  6, 99, 55],
       [18,  2,  4, 18],
       [32, 85, 72, 81]])

In [57]:
np.flip(b,axis=1)

array([[32, 85, 72, 81],
       [18,  2,  4, 18],
       [13,  6, 99, 55],
       [82, 22, 25, 17],
       [46, 66, 94, 24],
       [40, 15, 42,  6]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [59]:
# code
a

array([98, 15, 95, 95, 67, 10, 37, 96, 87, 56, 66, 98, 91, 41, 92])

In [60]:
np.put(a,[0,1],[110,530])

In [66]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
np.put(b,[0,4],[100,101])
b

array([[100,   1,   2,   3],
       [101,   5,   6,   7],
       [  8,   9,  10,  11]])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [62]:
# code
a

array([110, 530,  95,  95,  67,  10,  37,  96,  87,  56,  66,  98,  91,
        41,  92])

In [63]:
np.delete(a,[0,2,4])

array([530,  95,  10,  37,  96,  87,  56,  66,  98,  91,  41,  92])

In [71]:
np.delete(b,0,axis=0)

array([[101,   5,   6,   7],
       [  8,   9,  10,  11]])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.isin

if ndim >1 then numpy convert them 1d and then apply this function on them

In [72]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [73]:
np.intersect1d(m,n)

array([3, 4, 5])

In [74]:
np.setdiff1d(n,m)

array([6, 7])

In [75]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [78]:
np.isin(m,1)

array([ True, False, False, False, False])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals